name: ci

on:
  push:
    branches: [main]
    paths:
      - '**.ts'
      - '**.json'
  pull_request:
    paths:
      - '**.ts'
      - '**.json'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "14.x"
      - run: npm ci
      - run: npm test
