name: update

on:
  schedule:
    - cron: "0 13 * * 1"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - uses: technote-space/create-pr-action@v2
        with:
          EXECUTE_COMMANDS: |
            npm ci
            npm run update
            npm install
            npm audit fix
            npm test
          COMMIT_MESSAGE: 'chore(deps): update npm dependencies'
          COMMIT_NAME: 'GitHub Actions'
          COMMIT_EMAIL: 'no-reply@github.com'
          PR_BRANCH_NAME: 'chore-npm-update'
          PR_TITLE: 'chore(deps): update npm dependencies'
